<?php

function drlog_init() {

  // including the FirePHPCore librarie 
  $path = libraries_get_path('FirePHPCore') . '/lib/FirePHPCore/';

  require_once $path . 'FirePHP.class.php';
  require_once $path . 'fb.php';

  $firephp = FirePHP::getInstance(true);

  // debugging current user
  global $user;
  $username = 'Anonymous';
  if ($user->uid != 0) {
    $username = $user->name;
  }
  $firephp->group('User: ' . $username);
  $firephp->log($user);
  $firephp->groupEnd();

  // debugging meta tags (meta only)
  $head = explode("\n", drupal_get_html_head());
  $firephp->group('<meta>');
  $firephp->log($head);
  $firephp->groupEnd();

  // Path and node info
  $current_path = current_path();
  $firephp->group('Node info');
  $firephp->log($current_path, 'Current path');
  $firephp->log(request_path(), 'Request path');

  $nid = explode('/', $current_path);
  $node = node_load($nid[1]);
  $firephp->log($node, 'Node load');
  $firephp->groupEnd();

  // Server
  $firephp->group('Server');
  $firephp->log($_SERVER);
  $firephp->groupEnd();


  // css

  // js


}

/*
* Form alter
*/
function drlog_form_alter(&$form, &$form_state, $form_id){
  // debuggin the forms
  $firephp = FirePHP::getInstance(true);
  $firephp->group('Form found: ' . $form_id);
  $firephp->log($form);
  $firephp->groupEnd(); 
}
